# Generated by Gemini 3 flash


import os
import sys
import csv
from pyproj import Transformer

def get_net_info(net_file):
    """Extracts netOffset and projParameter from the SUMO network file."""
    net_offset = [0, 0]
    proj_params = ""
    
    with open(net_file, 'r') as f:
        for line in f:
            if '<location' in line:
                if 'netOffset="' in line:
                    offset_str = line.split('netOffset="')[1].split('"')[0]
                    net_offset = [float(x) for x in offset_str.split(',')]
                if 'projParameter="' in line:
                    proj_params = line.split('projParameter="')[1].split('"')[0]
                break
    return net_offset, proj_params

def convert_csv_to_wgs84(input_csv, output_csv, net_file="map.net.xml"):
    if not os.path.exists(net_file):
        print(f"Error: {net_file} not found.")
        sys.exit(1)
        
    net_offset, proj_params = get_net_info(net_file)
    OFFSET_X, OFFSET_Y = net_offset
    
    # Initialize transformer from UTM to WGS84
    transformer = Transformer.from_crs(proj_params, "EPSG:4326", always_xy=True)
    
    print(f"Converting CSV: {input_csv} to {output_csv}")
    
    with open(input_csv, 'r') as fin, open(output_csv, 'w', newline='') as fout:
        # GPSDAT is tab-separated
        reader = csv.reader(fin, delimiter='\t')
        writer = csv.writer(fout, delimiter='\t')
        
        count = 0
        for row in reader:
            if not row:
                continue
            try:
                # row format: [id, time, x, y, status, speed]
                veh_id, timestamp, x_sumo, y_sumo, status, speed = row
                
                # Coordinate Conversion
                x_utm = float(x_sumo) - OFFSET_X
                y_utm = float(y_sumo) - OFFSET_Y
                
                lon, lat = transformer.transform(x_utm, y_utm)
                
                # Write back with updated coordinates
                writer.writerow([veh_id, timestamp, f"{lon:.10f}", f"{lat:.10f}", status, speed])
                
                count += 1
                if count % 100000 == 0:
                    print(f"Processed {count} rows...")
            except (ValueError, IndexError) as e:
                print(f"Skipping invalid row: {row} - {e}")
                continue

    print(f"Successfully converted {count} rows.")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python convert_csv.py input.csv output.csv [net_file]")
        sys.exit(1)
        
    in_f = sys.argv[1]
    out_f = sys.argv[2]
    net_f = sys.argv[3] if len(sys.argv) > 3 else "map.net.xml"
    
    convert_csv_to_wgs84(in_f, out_f, net_f)
