#!/bin/bash
# generated by Gemini 3 flash antigravity
# https://www.researchgate.net/publication/270793563_Benchmarking_Trajectory_Matchers_with_SUMO

# ==============================================================================
# Full Pipeline for Replicating Trajectory Matching Experiment (ESM2014)
# ==============================================================================
# ==============================================================================
# 0. Argument Parsing
# ==============================================================================
OSM_FILE="yogyakarta.osm"
NOISE_METER=3.5
DELTA_T=1.0
NUM_VEHICLES=100
TRIP_DURATION=3600
USE_INTERNAL_LINKS="true"
CAN_REROUTE="true"

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --osm-file) OSM_FILE="$2"; shift ;;
        --noise-meter) NOISE_METER="$2"; shift ;; # see: disturb_gps() (x,y is in utm projected cartesian coordinate in meters)  https://github.com/eclipse-sumo/sumo/blob/main/tools/traceExporter.py
        --delta-t-seconds) DELTA_T="$2"; shift ;;
        --number-of-vehicles) NUM_VEHICLES="$2"; shift ;;
        --trip-duration-seconds) TRIP_DURATION="$2"; shift ;;
        --use-internal-links) USE_INTERNAL_LINKS="$2"; shift ;;
        --can-reroute) CAN_REROUTE="$2"; shift ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

# Calculate period: p = (end - begin) / n
PERIOD=$(python3 -c "print($TRIP_DURATION / $NUM_VEHICLES)")

# Setup conditional flags
INTERNAL_LINKS_FLAG=""
if [ "$USE_INTERNAL_LINKS" = "false" ]; then
    INTERNAL_LINKS_FLAG="--no-internal-links"
fi

REROUTE_FLAG=""
if [ "$CAN_REROUTE" = "false" ]; then
    REROUTE_FLAG="--device.rerouting.period 0"
fi

# Create tags for filenames (replacing dots with underscores)
NOISE_TAG=${NOISE_METER//./_}
DELTA_TAG=${DELTA_T//./_}

if [ ! -f "$OSM_FILE" ]; then
    echo "Error: File '$OSM_FILE' not found."
    exit 1
fi

# 1. Boost Library Workaround (Permanent fix: yay -S sumo --rebuild)
mkdir -p /tmp/sumo_libs
ln -sf /usr/lib/libboost_process.so.1.90.0 /tmp/sumo_libs/libboost_process.so.1.89.0
ln -sf /usr/lib/libboost_filesystem.so.1.90.0 /tmp/sumo_libs/libboost_filesystem.so.1.89.0
ln -sf /usr/lib/libboost_context.so.1.90.0 /tmp/sumo_libs/libboost_context.so.1.89.0
ln -sf /usr/lib/libboost_date_time.so.1.90.0 /tmp/sumo_libs/libboost_date_time.so.1.89.0
export LD_LIBRARY_PATH=/tmp/sumo_libs:$LD_LIBRARY_PATH

# 2. Network Conversion (OSM -> SUMO NET)
# Added memory-saving simplification flags
echo "Converting OSM to SUMO network..."
netconvert --osm-files "$OSM_FILE" \
           -o map.net.xml \
           --geometry.remove \
           --junctions.join \
           --roundabouts.guess \
           --remove-edges.isolated \
           --keep-edges.by-vclass passenger \
           $INTERNAL_LINKS_FLAG \
           --xml-validation never

# https://sumo.dlr.de/docs/Geo-Coordinates.html
netconvert --sumo-net-file map.net.xml --plain-output-prefix plain --proj.plain-geo


# 3. Generate Trips (Random Vehicles) https://sumo.dlr.de/docs/Tools/Trip.html
echo "Generating $NUM_VEHICLES vehicle trips over $TRIP_DURATION seconds (period: $PERIOD)..."
python /usr/share/sumo/tools/randomTrips.py \
    -n map.net.xml \
    --min-distance 1000 \
    --end "$TRIP_DURATION" \
    --period "$PERIOD" \
    --validate \
    --duarouter-routing-algorithm CH \
    -o trips.trips.xml

# 4. Routing (Calculating routes using Contraction Hierarchies) https://sumo.dlr.de/docs/duarouter.html
echo "Calculating routes..."
duarouter -n map.net.xml \
    -r trips.trips.xml \
    --output-file routes.rou.xml \
    --routing-algorithm CH \
    --write-trips.geo \
    --ignore-errors \
    --xml-validation never

# 5. Simulation (Running the scenario)
echo "Running SUMO simulation with step-length $DELTA_T..."
sumo -n map.net.xml \
    -r routes.rou.xml \
    --step-length "$DELTA_T" \
    $INTERNAL_LINKS_FLAG \
    --no-step-log \
    --xml-validation never \
    $REROUTE_FLAG \
    --fcd-output perfect_trajectories.xml.gz

# 6. Trace Generation (Generating noisy synthetic GPS data)
echo "Exporting noisy trajectories with gps-blur ${NOISE_METER}m and delta-t ${DELTA_T}s..."
python /usr/share/sumo/tools/traceExporter.py \
    --fcd-input perfect_trajectories.xml.gz \
    --gps-blur "$NOISE_METER" \
    --gpsdat-output "noisy_data_${NOISE_TAG}_${DELTA_TAG}.csv" \
    --delta-t "$DELTA_T"

echo "Full pipeline complete."
echo "Ground Truth: perfect_trajectories.xml.gz"
echo "Noisy GPSDAT (with speed): noisy_data_${NOISE_TAG}_${DELTA_TAG}.csv"


echo "Converting CSV to WGS84..."
python convert_csv.py "noisy_data_${NOISE_TAG}_${DELTA_TAG}.csv" "noisy_data_wgs84_${NOISE_TAG}_${DELTA_TAG}.csv"

echo "All conversions complete. Final WGS84 files:"
echo " - noisy_data_wgs84_${NOISE_TAG}_${DELTA_TAG}.csv"










