#!/bin/bash
# Generated by Gemini 3 flash (AI Slop)

# automate_dimacs_test.sh
# Automates the DIMACS 9th Challenge testing process.

set -e

usage() {
    echo "Usage: $0 -m <map_name> -n <num_sources>"
    echo "Example: $0 -m CAL -n 50"
    exit 1
}

MAP_NAME=""
NUM_SOURCES=""

while getopts "m:n:" opt; do
    case $opt in
        m) MAP_NAME="$OPTARG" ;;
        n) NUM_SOURCES="$OPTARG" ;;
        *) usage ;;
    esac
done

if [ -z "$MAP_NAME" ] || [ -z "$NUM_SOURCES" ]; then
    usage
fi

ROOT_DIR=$(pwd)
DIMACS_DIR="$ROOT_DIR/dimacs-ch9-1.1"
INPUT_DIR="$DIMACS_DIR/inputs/USA-road-t"
SCRIPTS_DIR="$DIMACS_DIR/scripts"
SOLVER_DIR="$DIMACS_DIR/solvers/mlb-dimacs"
GO_DIR="$ROOT_DIR/Navigatorx"
GO_SOURCE="eval/crp_alt/dimacs_9_shortest_path_alt/main.go"
GO_BINARY="$GO_DIR/dimacs_solver"

echo "=== Starting DIMACS Test for $MAP_NAME with $NUM_SOURCES sources ==="

# 1. Download files
mkdir -p "$INPUT_DIR"
echo "--- Checking/Downloading data files ---"

GR_FILE="USA-road-t.$MAP_NAME.gr"
CO_FILE="USA-road-d.$MAP_NAME.co"

if [ ! -f "$INPUT_DIR/$GR_FILE" ]; then
    echo "Downloading $GR_FILE.gz..."
    wget -c "https://www.diag.uniroma1.it/~challenge9/data/USA-road-t/$GR_FILE.gz" -O "$INPUT_DIR/$GR_FILE.gz"
    gunzip "$INPUT_DIR/$GR_FILE.gz"
fi

if [ ! -f "$INPUT_DIR/$CO_FILE" ]; then
    echo "Downloading $CO_FILE.gz..."
    wget -c "https://www.diag.uniroma1.it/~challenge9/data/USA-road-d/$CO_FILE.gz" -O "$INPUT_DIR/$CO_FILE.gz"
    gunzip "$INPUT_DIR/$CO_FILE.gz"
fi

# 2. Run Perl script to generate .ss file
echo "--- Generating query file (.ss) ---"
cd "$SCRIPTS_DIR"
export MAP="$MAP_NAME"
export MINNSRC="$NUM_SOURCES"
perl genUSA-road-t.ss.pl

SS_FILE="$INPUT_DIR/USA-road-t.$MAP_NAME.ss"

# 3. Build and Run Go Routing Engine
echo "--- Building Go Routing Engine ---"
cd "$GO_DIR"
go build -o dimacs_solver "$GO_SOURCE"

echo "--- Running Go Routing Engine ---"
CHK_FILE="$ROOT_DIR/DIMACS_9_USA_$MAP_NAME.ss.chk"
./dimacs_solver \
    -input_nodes "$INPUT_DIR/$CO_FILE" \
    -input_edges "$INPUT_DIR/$GR_FILE" \
    -input_queries "$SS_FILE" \
    -output_name "$CHK_FILE"

# 4. Run Benchmark Solver (sqC.exe)
echo "--- Running Benchmark Solver (sqC.exe) ---"
cd "$SOLVER_DIR"
RES_FILE="my_results.ss.res"
# Remove old result file if exists
rm -f "$RES_FILE"

# Use relative paths to stay under the 100-character buffer limit in sqC.exe
REL_GR_FILE="../../inputs/USA-road-t/$GR_FILE"
REL_SS_FILE="../../inputs/USA-road-t/USA-road-t.$MAP_NAME.ss"

./sqC.exe "$REL_GR_FILE" "$REL_SS_FILE" "$RES_FILE"

# 5. Compare Results
echo "--- Comparing Checksums ---"
cd "$ROOT_DIR"
python3 scripts/compare_checksums.py "$SS_FILE" "$SOLVER_DIR/$RES_FILE" "$CHK_FILE"

echo "=== DIMACS Test Completed Successfully ==="








