import sys
import os
# Generated by gemini 3 flash (AI Slop)

def parse_ss_file(ss_file):
    sources = []
    with open(ss_file, 'r') as f:
        for line in f:
            if line.startswith('s '):
                sources.append(int(line.split()[1]))
    return sources

def parse_res_file(res_file):
    checksums = []
    with open(res_file, 'r') as f:
        for line in f:
            if line.startswith('d '):
                # Format: d <checksum>
                parts = line.split()
                if len(parts) == 2:
                    checksums.append(int(parts[1]))
    return checksums

def parse_chk_file(chk_file):
    results = {}
    with open(chk_file, 'r') as f:
        for line in f:
            if line.startswith('d '):
                # Format: d <source> <checksum>
                parts = line.split()
                if len(parts) == 3:
                    results[int(parts[1])] = int(parts[2])
    return results

def main():
    if len(sys.argv) != 4:
        print("Usage: python compare_checksums.py <ss_file> <res_file> <chk_file>")
        sys.exit(1)

    ss_file = sys.argv[1]
    res_file = sys.argv[2]
    chk_file = sys.argv[3]

    print(f"Comparing {res_file} and {chk_file} using sources from {ss_file}")

    try:
        sources = parse_ss_file(ss_file)
        benchmark_checksums = parse_res_file(res_file)
        go_results = parse_chk_file(chk_file)
    except Exception as e:
        print(f"Error reading files: {e}")
        sys.exit(1)

    if len(sources) != len(benchmark_checksums):
        print(f"Warning: Number of sources ({len(sources)}) does not match benchmark checksums ({len(benchmark_checksums)})")
    
    mismatches = []
    for i, source in enumerate(sources):
        if i >= len(benchmark_checksums):
            print(f"Missing benchmark checksum for source {source}")
            continue
        
        bench_val = benchmark_checksums[i]
        go_val = go_results.get(source)

        if go_val is None:
            print(f"Source {source} not found in Go results ({chk_file})")
            mismatches.append(source)
            continue

        if bench_val != go_val:
            print(f"Mismatch for source {source}: Benchmark={bench_val}, Go={go_val}")
            mismatches.append(source)
        else:
            print(f"Source {source}: OK ({bench_val})")

    if not mismatches:
        print("\nSUCCESS: All checksums match!")
    else:
        print(f"\nFAILURE: Found {len(mismatches)} mismatches.")
        sys.exit(1)

if __name__ == "__main__":
    main()
